services:

  #---------------- REDIS ----------------
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal

  # ---------------- AUTH DATABASE ----------------
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- AUTH SERVICE ----------------
  auth-service:
    container_name: auth-service
    build: ./auth-service
    image: auth-service
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      JWT_SECRET: bXkgbmFtZSBpcyBqYXlkZWVwIGJhcml5YSBhbmQgaSB3aWxsIGJlIHN1Y2Nlc3NmdWwgaW4gdGhpcyB5ZWFy
      JWT_ACCESS_TOKEN_EXPIRATION: 900000
      JWT_REFRESH_TOKEN_EXPIRATION: 604800000

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    networks:
      - internal

  # ---------------- PRODUCT DATABASE ----------------
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- PRODUCT SERVICE ----------------
  product-service:
    container_name: product-service
    build: ./product-service
    image: product-service
    depends_on:
      - product-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    networks:
      - internal

  # ---------------- INVENTORY DATABASE ----------------
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- INVENTORY SERVICE ----------------
  inventory-service:
    container_name: inventory-service
    build: ./inventory-service
    image: inventory-service
    depends_on:
      - inventory-db
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
    networks:
      - internal

  # ---------------- ORDER DATABASE ----------------
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- ORDER SERVICE ----------------
  order-service:
    container_name: order-service
    build: ./order-service
    image: order-service
    depends_on:
      - order-db
      - inventory-service
      - payment-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    networks:
      - internal

  # ---------------- PAYMENT DATABASE ----------------
  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- PAYMENT SERVICE ----------------
  payment-service:
    container_name: payment-service
    build: ./payment-service
    image: payment-service
    depends_on:
      - payment-db
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    networks:
      - internal

  # ---------------- NOTIFICATION DATABASE ----------------
  notification-db:
    image: postgres:15
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - internal

  # ---------------- NOTIFICATION SERVICE ----------------
  notification-service:
    container_name: notification-service
    build: ./notification-service
    image: notification-service
    depends_on:
      - notification-db
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    networks:
      - internal

volumes:
  auth_data:
  product_data:
  inventory_data:
  order_data:
  payment_data:
  notification_data:
  redis_data:

networks:
  internal:
    driver: bridge
