server:
  port: 8080

jwt:
  secret: bXkgbmFtZSBpcyBqYXlkZWVwIGJhcml5YSBhbmQgaSB3aWxsIGJlIHN1Y2Nlc3NmdWwgaW4gdGhpcyB5ZWFy

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
