# Server
server.port=8083
spring.application.name=order-service

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG

# Redis
spring.data.redis.port=6379
spring.data.redis.host=redis
spring.data.redis.timeout=60000

# Lettuce
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=1ms

# Kafka
spring.kafka.bootstrap-servers=kafka-broker:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html